hyperparameters:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 15
  img_size: [256, 256]

data:
  classes: ["Benign", "InSitu", "Invasive", "Normal"]
  split: [0.8, 0.1, 0.1]
  normalisation:
    imagenet:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    bach: # TODO
      mean: [0.7169684767723083, 0.6170014142990112, 0.842685878276825]
      std: [0.1456914097070694, 0.1676328033208847, 0.10762365907430649]

ensemble1:
  models:
    - name: "resnet101"
      normalisation: "imagenet"
    - name: "densenet161_1"
      normalisation: "imagenet"
    - name: "densenet161_2"
      normalisation: "bach"

ensemble2:
  models:
    - name: "resnet18"
      normalisation: "imagenet"
    - name: "densenet121_1"
      normalisation: "imagenet"
    - name: "densenet121_2"
      normalisation: "bach"

execution:
  num_workers: 2

paths:
  img_dir: "data/ICIAR2018_BACH_Challenge/Photos"
  best_model_path: "best_model.pth"
  history_dir: "history"
